name: Generate Artifacts
 
on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Artifact name to upload'
        required: true
 
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Artifacts
        run: |
          mkdir artifacts
          echo "Artifact content" > artifacts/my_artifact.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: artifacts
