name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      targetEnvironment:
        description: 'The target environment to deploy to'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build project
      run: echo "Building the project..."

  approval:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event.inputs.targetEnvironment == 'QA' || github.event.inputs.targetEnvironment == 'UAT' || github.event.inputs.targetEnvironment == 'PROD' }}

    steps:
    - name: Manual Approval
      id: approval
      uses: hmarr/auto-approve-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Approver Name
      run: echo "APPROVER=${{ github.actor }}" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest
    needs: [build, approval]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy project
      run: echo "Deploying the project..."

    - name: Send Power Automate Notification
      run: |
        echo ${{ env.APPROVER }}
