name: Use Artifacts
 
on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Artifact name to download'
        required: true
 
jobs:
  use:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifact
        run: |
          curl -L -o artifact.zip "${{ github.event.inputs.artifact_url }}"
          unzip artifact.zip -d ./downloaded-artifact

      - name: Deploy build artifact
        run: |
          cat ./downloaded-artifact/output/build.txt
